// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Scribe.Data.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedDeleteFlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedDeleteFlag));
        
        string IMigrationMetadata.Id
        {
            get { return "201602071603250_AddedDeleteFlag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
